# Generated by Django 3.0.7 on 2020-11-20 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('linkid', models.AutoField(primary_key=True, serialize=False)),
                ('userrole', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=50)),
                ('appname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)])),
                ('userrole', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-userid'],
            },
        ),
    ]
